---
title: "Rmarkdown for Final test"
author: "Ki Wook LEE"
date: "`r Sys.Date()`"
output: github_document
---

###Load the library & data
```{r warning=F, message=F}
library(tableone);library(data.table);library(magrittr);library(survival);library(jstable)
url <- "https://raw.githubusercontent.com/jinseob2kim/lecture-snuhlab/master/data/example_g1e.csv"
dt <- fread(url, header=T)

```

```{r}
head(dt)
```

<br/>

### Q.1 Table 만들기
```{r}
data = dt[,c('HGHT',"WGHT", 'BMI', 'HDL', 'LDL', 'Q_SMK_YN', 'Q_HBV_AG','EXMD_BZ_YYYY')]
data$Q_SMK_YN = as.factor(data$Q_SMK_YN)
data$Q_HBV_AG = as.factor(data$Q_HBV_AG)
```
```{r }
CreateTableOne(vars = colnames(data)[-8], strata= 'EXMD_BZ_YYYY', data=data)
```

<br/>

### Q.2 선형회귀, 로지스틱, 콕스생존분석 table 만들기
#### Q.2-1
```{r}
head(colon)

lin.reg = glm(time ~ rx + age + sex, data=colon)
table1 = glmshow.display(lin.reg)
```
```{r echo=F}
knitr::kable(table1$table, caption = table1$first.line)
```

#### Q.2-2
```{r}

head(colon)

log.reg = glm(status ~ rx +age + sex, data=colon, family = binomial)
table2 = glmshow.display(log.reg)

```
```{r echo=F}
knitr::kable(table2$table, caption = table2$first.line)

```

#### Q.2-3
```{r}
head(colon)

cox.pro = coxph(Surv(time, status) ~ rx + age + sex, data = colon, model = T)
table3 <- cox2.display(cox.pro)

```
```{r echo=F}
knitr::kable(table3$table, caption = table3$caption)
```



